baseURL = "https://gabrielcolson.fr"
title = "Gabriel Colson"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

[params]
  author = "Gabriel Colson"
  description = "A blog about stuff (mostly programming)."
  share = true
  showLanguageSwitcher = false

  [params.social]
    rss = true
    linkedin = "https://www.linkedin.com/in/gabriel-colson/"
    github = "https://github.com/gabrielcolson"

  [params.prismJS]
    enable = true
    theme = ""

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
